baseurl      = "https://distracted-goldberg-0d469f.netlify.app/"
title        = "Monica Blog"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10
publishDir = "docs"



[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "DevOps & SDET"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "My new homepage & blog"
  keywords = "homepage, blog, about"
  images = [""]

  # Set a background for the homepage
  #backgroundImage = "img/bg1.jpg"
  
  #Enable theme toggle
  enableThemeToggle = true
  justifyContent = false  # Set "text-align: justify" to .post-content.
  
  
  # Uncomment this if you want a portrait on your start page
  #
  [params.portrait]
    path     = "img/moni.jpeg"
    alt      = "Monica"
    maxWidth = "100px"


  # Social icons
  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/wondermony"

  [[params.social]]
    name = "polywork"
    url  = "https://www.polywork.com/wondermony"

  [[params.social]]
    name = "github"
    url  = "https://github.com/monicalimachi"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/monica-limachi-lopez/"    

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "Monica Limachi"
    subtitle = "DevOps"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "monica@home"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "projects"
    name       = "Experience"
    url        = "/Projects"

  [[menu.main]]
    identifier = "about"
    name       = "About Me"
    url        = "/About"

[privacy]
  [privacy.disqus]
    disable = false
  [privacy.googleAnalytics]
    anonymizeIP = false
    disable = false
    respectDoNotTrack = false
    useSessionStorage = false
  [privacy.instagram]
    disable = false
    simple = false
  [privacy.twitter]
    disable = false
    enableDNT = false
    simple = false
  [privacy.vimeo]
    disable = false
    enableDNT = false
    simple = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = false



