[build]
publish = "docs"
command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.92.2"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "false"

[context.split1]
command = "hugo --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.92.2"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.92.2"

[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.92.2"

[context.next.environment]
HUGO_ENABLEGITINFO = "false"

[[redirects]]
from = "/npmjs/*"
to = "/npmjs/"
status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    # Content-Security-Policy = "connect-src api.amplitude.com; fonts cdnjs.cloudflare.com fonts.gstatic.com; img 'self' monicalimachi.cloud www.monicalimachi.cloud; script-src-elem 'unsafe-inline' cdn.amplitude.com cdnjs.cloudflare.com monicalimachi.cloud 'self'; style-src-attr 'unsafe-inline'; style-src-elem 'self' 'unsafe-inline' cdnjs.cloudflare.com fonts.googleapis.com monicalimachi.cloud www.monicalimachi.cloud"
    # Content-Security-Policy-Report-Only = "default-src 'none'; form-action 'none'; frame-ancestors 'none'; report-uri https://report-uri.com/r/d/csp/wizard"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=2592000"
    Feature-Policy = "vibrate 'none'; geolocation 'none'; midi 'none'; notifications 'none'; push 'none'; sync-xhr 'none'; microphone 'none'; camera 'none'; magnetometer 'none'; gyroscope 'none'; speaker 'none'; vibrate 'none'; fullscreen 'none'; payment 'none'"    